export const actionTypes = {
  RESET_COMMON: 'RESET_COMMON',

  HANDLE_REGISTER: 'HANDLE_REGISTER',
  REGISTER_FAIL: 'REGISTER_FAIL',

  HANDLE_LOGIN: 'HANDLE_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',

  RESET_MESSAGE: 'RESET_MESSAGE',

  HANDLE_LOGOUT: 'HANDLE_LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'LOGOUT_FAIL',

  HANDLE_REFRESH: 'HANDLE_REFRESH',
  REFRESH_SUCCESS: 'REFRESH_SUCCESS',
  REFRESH_FAIL: 'REFRESH_FAIL',

  BANK_SELECTED: 'BANK_SELECTED',

  BANK_SAVE: 'BANK_SAVE',
  BANK_SAVE_SUCCESS: 'BANK_SAVE_SUCCESS',
  BANK_SAVE_FAIL: 'BANK_SAVE_FAIL',

  USER_ALL_BANK: 'USER_ALL_BANK',
  USER_ALL_BANK_SUCCESS: 'USER_ALL_BANK_SUCCESS',

  BANK_UPDATE: 'BANK_UPDATE',
  BANK_UPDATE_SUCCESS: 'BANK_UPDATE_SUCCESS',
  BANK_UPDATE_FAIL: 'BANK_UPDATE_FAIL',

  BANK_DELETE: 'BANK_DELETE',
  BANK_DELETE_FAIL: 'BANK_DELETE_FAIL',

  WITHDRAW_BANK: 'WITHDRAW_BANK',
  WITHDRAW_BANK_SUCCESS: 'WITHDRAW_BANK_SUCCESS',
  WITHDRAW_BANK_FAIL: 'WITHDRAW_BANK_FAIL',

  WITHDRAW_CARD: 'WITHDRAW_CARD',
  WITHDRAW_CARD_SUCCESS: 'WITHDRAW_CARD_SUCCESS',
  WITHDRAW_CARD_FAIL: 'WITHDRAW_CARD_FAIL',

  AMOUNT_TRANSFER: 'AMOUNT_TRANSFER',
  AMOUNT_TRANSFER_SUCCESS: 'AMOUNT_TRANSFER_SUCCESS',

  UPDATEINFO: 'UPDATEINFO',
  UPDATEINFO_SUCCESS: 'UPDATEINFO_SUCCESS',

  UPDATEPROFILE: 'UPDATEPROFILE',
  UPDATEPROFILE_SUCCESS: 'UPDATEPROFILE_SUCCESS',
};
export default actionTypes;
