export const API_URL = {
  DOMAIN: '',
  REST_COMMON: '/resetCommon',
  REGISTER: '/register',
  LOGIN: '/login',
  LOGOUT: '/logout',
  REFRESH: '/refresh',
  VERIFYINFO: '/verify/info',

  ///////Sin////
  HEROBANNER: '/home/heroBanner',
  BANKS: '/users/banks',
  NOTIFICATION: '/notification',
  HIDDENNOTIFY:'/hiddenNotify',
  VIEWEDNOTIFY:'/viewedNotify',
  LODE:'/lode',
  LODE2URL: '/lode2Url',
  LODEVIRTUAL: '/lodeVirtualUrl',
  LODEURL: '/lodeUrl',
  GAMES: '/game',
  SLOT: '/slot',
  CASINO: '/casino',
  HOTMATCH: '/hotmatch',
  USER: '/user',
  PAYMENT: '/payment',
  TRANSACTIONS: '/transactions',
  LSBALL: '/lsbAll',
  LSBET: '/lsbet',
  LSBATHENA: '/lsbAthena',
  TRANSFER: '/athena/transfer',
  UPDATEINFO: '/updateinfo',
  UPDATEPASSWORD: '/updatePassword',
  CHECKEMAIL: '/verifyEmail',
  FORGOTPASSWORD: '/forgotPasswordV2',
  SPORTLINK: '/athena/matchUrl',
  SINSPORTLINK: '/athena/multiSportUrl',
  ESPORTLINK:'/athena/esportsUrl',
  VSPORTURL: '/athena/multiVSportUrl',
  SPORTURL: '/athena/sportUrl',
  KSPORTURL: '/ksportUrl',
  TSPORTURL: '/tsport/multiSportUrl',
  ISPORTURL: '/imsportUrl?sportType=sport',
  SSPORTURL: '/ssport/multiSportUrl',
  CASINOLINK: '/casinoUrl',
  COMMISSIONS: '/commissions',
  POSTSLIST: '/categories/posts',
  POSTDETAIL: '/post',
  POSTS: '/posts',
  ACCOUNT: '/account',
  CATEGORY: '/category',
  TRANSACTION: "/lsgd",
  HISTORYBET: "/lsb",
  STATISTIC: "/statistic",
  GAMEURL:'/gameUrl',
BET_TRANSACTION: "/lsb",
};
